apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextshop
  labels:
    app: nextshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextshop
  template:
    metadata:
      labels:
        app: nextshop
    spec:
      containers:
      - name: nextshop
        image: cosmicenvy/nextshop:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextshop-service
spec:
  selector:
    app: nextshop
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30050
